name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_USER_PASSWORD }}
        run: |
          # Build your Docker image here
          docker build -t your-docker-image-name .
          
          # Log in to Docker Hub
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

          # Push the Docker image to Docker Hub
          docker push your-docker-image-name

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
